import { Crosshair, ShieldCheck, RefreshCw } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { createCheckIn, getPointLedger, getSpots, precheckSpot, type PositionInput } from '../../api/client';
import type { Spot } from '../../types/spot';
import { CheckInMap } from '../../components/CheckInMap';
import { formatPoints } from '../../lib/format';

type LocationState = 'idle' | 'requesting' | 'measured' | 'denied' | 'inaccurate' | 'out-of-range' | 'unsupported';
type CheckInResult = { status: 'success' | 'pending' | 'failure'; points?: number; message: string };
const RefreshReresh = RefreshCw;

export function CheckInPage() {
  const [state, setState] = useState<LocationState>('idle'); const [accuracy, setAccuracy] = useState<number | null>(null); const [position, setPosition] = useState<{ lat: number; lng: number } | null>(null); const [selectedSpot, setSelectedSpot] = useState<Spot | null>(null); const [checkInMessage, setCheckInMessage] = useState(''); const [precheckLoading, setPrecheckLoading] = useState(false); const [checkInLoading, setCheckInLoading] = useState(false); const [precheckResult, setPrecheckResult] = useState<{ eligible: boolean; distanceM?: number; allowedRadiusM?: number; reasons?: string[] } | null>(null); const [checkInResult, setCheckInResult] = useState<CheckInResult | null>(null);
  useEffect(() => { if (!navigator.geolocation) { setState('unsupported'); return; } setState('requesting'); navigator.geolocation.getCurrentPosition(({ coords }) => { const nextAccuracy = Math.round(coords.accuracy); setAccuracy(nextAccuracy); setPosition({ lat: coords.latitude, lng: coords.longitude }); setState(nextAccuracy > 50 ? 'inaccurate' : 'measured'); }, (error) => setState(error.code === error.PERMISSION_DENIED ? 'denied' : 'idle'), { enableHighAccuracy: true, timeout: 10000, maximumAge: 0 }); }, []);
  useEffect(() => { setPosition((current) => current ? { ...current, accuracy } : current); }, [accuracy]);
  useEffect(() => { if (!navigator.permissions?.query) return; navigator.permissions.query({ name: 'geolocation' }).then((permission) => { if (permission.state === 'denied') setState('denied'); }); }, []);
  const spotsQuery = useQuery({ queryKey: ['check-in-spots'], queryFn: () => getSpots({ areaCode: '1', sigunguCode: '23', limit: 20 }) });
  const ledgerQuery = useQuery({ queryKey: ['point-ledger'], queryFn: getPointLedger, retry: false });
  const requestLocation = () => { if (!navigator.geolocation) { setState('unsupported'); return; } setCheckInMessage(''); setState('requesting'); navigator.geolocation.getCurrentPosition(({ coords }) => { const nextAccuracy = Math.round(coords.accuracy); setAccuracy(nextAccuracy); setPosition({ lat: coords.latitude, lng: coords.longitude }); setState(nextAccuracy > 50 ? 'inaccurate' : 'measured'); }, (error) => setState(error.code === error.PERMISSION_DENIED ? 'denied' : 'idle'), { enableHighAccuracy: true, timeout: 10000, maximumAge: 0 }); };
  const runPrecheck = async () => { if (!position || !selectedSpot || accuracy === null) return; setPrecheckLoading(true); setPrecheckResult(null); setCheckInMessage('인증 가능 여부를 확인하는 중입니다.'); const input: PositionInput = { lat: position.lat, lng: position.lng, accuracyM: accuracy, capturedAt: new Date().toISOString() }; try { const result = await precheckSpot(selectedSpot.id, input) as { data?: { eligible?: boolean; distanceM?: number; allowedRadiusM?: number; reasons?: string[] } }; const data = result.data; const eligible = data?.eligible === true; setPrecheckResult({ eligible, distanceM: data?.distanceM, allowedRadiusM: data?.allowedRadiusM, reasons: data?.reasons }); setState(eligible ? 'measured' : 'out-of-range'); setCheckInMessage(eligible ? `인증할 수 있는 장소예요. 현재 거리 ${Math.round(data?.distanceM ?? 0)}m` : `체크인할 수 없어요. ${data?.reasons?.join(', ') ?? '범위를 확인해주세요.'}`); } catch (error) { setPrecheckResult(null); setCheckInMessage(error instanceof Error ? error.message : '사전 인증 확인에 실패했습니다.'); } finally { setPrecheckLoading(false); } };
  const runCheckIn = async () => { if (!position || !selectedSpot || accuracy === null || !precheckResult?.eligible) return; setCheckInLoading(true); const input: PositionInput = { lat: position.lat, lng: position.lng, accuracyM: accuracy, capturedAt: new Date().toISOString() }; try { const result = await createCheckIn(selectedSpot.id, input) as { data?: { points?: number; status?: string; message?: string } }; const data = result.data; const pending = data?.status === 'PENDING'; setCheckInResult({ status: pending ? 'pending' : 'success', points: data?.points, message: data?.message ?? (pending ? '인증 결과를 확인하고 있어요.' : '체크인이 완료되었습니다.') }); } catch (error) { setCheckInResult({ status: 'failure', message: error instanceof Error ? error.message : '체크인 처리에 실패했습니다.' }); } finally { setCheckInLoading(false); } };
  const copy = { idle: ['위치 권한을 확인하기 전이에요', '현재 위치를 확인하면 가까운 체크인 장소를 안내해드려요.', '위치 권한 요청하기'], requesting: ['현재 위치를 확인하고 있어요', '잠시만 기다려주세요. 정확한 위치를 측정하고 있어요.', '위치 확인 중'], measured: ['현재 위치를 확인했어요', `GPS 정확도는 ${accuracy ?? '-'}m예요. 장소를 선택해 인증 가능 여부를 확인해보세요.`, '다시 측정하기'], denied: ['위치 권한이 필요해요', '브라우저 설정에서 위치 권한을 허용한 뒤 다시 시도해주세요.', '다시 요청하기'], inaccurate: ['GPS 정확도가 부족해요', `현재 정확도는 ${accuracy ?? '-'}m예요. 50m 이내가 되도록 다시 측정해주세요.`, '다시 측정하기'], 'out-of-range': ['아직 체크인 범위 밖이에요', '선택한 장소에서 100m 이내로 이동하면 체크인할 수 있어요.', '현재 위치 다시 확인'], unsupported: ['위치 기능을 사용할 수 없어요', '이 브라우저에서는 위치 정보를 지원하지 않습니다.', '다시 시도하기'] }[state];
  const isRequesting = state === 'requesting' || precheckLoading || checkInLoading;
  return <main className="page check-in-page"><header className="simple-header"><p className="eyebrow"><Crosshair size={15} /> 현장 인증</p><h1>가까운 플래그를 찾아볼까요?</h1><p>위치는 인증 순간에만 사용하며 이동 경로를 저장하지 않습니다.</p></header><CheckInMap position={position} spots={spotsQuery.data?.data ?? []} selectedSpot={selectedSpot} onSelect={setSelectedSpot} /><section className="check-in-card"><div><span className={`status-dot status-dot--${state}`} /><small>{copy[0]}</small></div><h2>{copy[1]}</h2><select aria-label="체크인 장소 선택" value={selectedSpot?.id ?? ''} onChange={(event) => { setSelectedSpot(spotsQuery.data?.data.find((spot) => spot.id === Number(event.target.value)) ?? null); setPrecheckResult(null); setCheckInResult(null); setCheckInMessage(''); }}><option value="">체크인할 장소를 선택하세요</option>{spotsQuery.data?.data.map((spot) => <option key={spot.id} value={spot.id}>{spot.title}</option>)}</select><button type="button" className="primary-button" disabled={isRequesting} onClick={requestLocation}>{isRequesting ? <><RefreshReresh className="spin" size={19} /> {copy[2]}</> : <><Crosshair size={19} /> {copy[2]}</>}</button>{position && selectedSpot && accuracy !== null && accuracy <= 50 && <button type="button" className="primary-button check-in-submit" disabled={precheckLoading} onClick={runPrecheck}>{precheckLoading ? '확인 중...' : '선택한 장소 인증 가능 여부 확인'}</button>}{precheckResult?.eligible && <><p className="precheck-success" role="status">반경 {precheckResult.allowedRadiusM ?? 100}m 이내 인증 가능</p><button type="button" className="primary-button check-in-submit" disabled={checkInLoading} onClick={() => setCheckInResult({ status: 'failure', message: '인증 확인이 필요합니다.' })}>인증하기</button></>}{checkInMessage && <p className="auth-error" role="status">{checkInMessage}</p>}<p className="privacy-note"><ShieldCheck size={15} /> GPS 정확도와 거리를 서버에서 확인합니다.</p></section>{checkInResult && <div className="check-in-modal-backdrop" role="presentation"><section className={`check-in-modal check-in-modal--${checkInResult.status}`} role="dialog" aria-modal="true" aria-label="체크인 결과"><h2>{checkInResult.status === 'success' ? '체크인 완료' : checkInResult.status === 'pending' ? '인증 확인 중' : '체크인에 실패했어요'}</h2><p>{checkInResult.message}</p>{checkInResult.points !== undefined && <strong className="check-in-modal__points">+{checkInResult.points}P</strong>}<button type="button" className="primary-button" onClick={() => setCheckInResult(null)}>확인</button></section></div>}</main>;
}
