import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { useQuery } from '@tanstack/react-query';
import { CheckInMap, getCheckInRadius, getSpotMarkerStatus, type MarkerStatus } from '../../components/CheckInMap';
import { createCheckIn, getSpots, precheckSpot, type PositionInput } from '../../api/client';
import { CheckInApiError } from '../../types/api';
import { ensureTestAuthToken } from '../auth/auth';
import { calculateDistanceMeters, CHECK_IN_RADIUS_METERS, formatDistance } from './distance';
import type { Spot } from '../../types/spot';

const DEFAULT_LOCATION = { lat: 37.58, lng: 126.98 };
const MOCK_SPOTS: Spot[] = [
  { id: 910001, title: '경복궁', address: '서울 종로구 사직로 161', contentTypeId: 12, isDecliningArea: false, imageUrl: null, status: 'ACTIVE', checkInEnabled: true, location: { lat: 37.5796, lng: 126.977 } },
  { id: 910002, title: '북촌문화센터', address: '서울 종로구 계동길 37', contentTypeId: 14, isDecliningArea: false, imageUrl: null, status: 'ACTIVE', checkInEnabled: true, location: { lat: 37.5801, lng: 126.9801 } },
  { id: 910003, title: '창덕궁', address: '서울 종로구 율곡로 99', contentTypeId: 12, isDecliningArea: false, imageUrl: null, status: 'ACTIVE', reviewStatus: 'PENDING', location: { lat: 37.5794, lng: 126.991 } },
  { id: 910004, title: '광화문광장', address: '서울 종로구 세종대로 172', contentTypeId: 12, isDecliningArea: false, status: 'ACTIVE', imageUrl: null, checkInEnabled: true, checkInCompleted: true, location: { lat: 37.5759, lng: 126.9769 } },
];
const STATUS_LABEL: Record<MarkerStatus, string> = { LOCKED: '🔒 인증 범위 밖', AVAILABLE: '🟢 현장 인증 가능', PENDING: '⏳ 인증 심사 진행 중', COMPLETED: '✅ 현장 인증 완료' };

export function CheckInTestPage() {
  const [position, setPosition] = useState(DEFAULT_LOCATION); const [latitude, setLatitude] = useState(String(DEFAULT_LOCATION.lat)); const [longitude, setLongitude] = useState(String(DEFAULT_LOCATION.lng)); const [error, setError] = useState(''); const [spots, setSpots] = useState<Spot[]>(MOCK_SPOTS); const [selectedSpot, setSelectedSpot] = useState<Spot | null>(null); const [statusOverrides, setStatusOverrides] = useState<Record<string, MarkerStatus>>({}); const [notice, setNotice] = useState(''); const [rewardPopup, setRewardPopup] = useState<{ points: number; message: string } | null>(null); const [loading, setLoading] = useState(false); const [authReady, setAuthReady] = useState(false);
  useEffect(() => { ensureTestAuthToken(); setAuthReady(true); }, []);
  const spotsQuery = useQuery({ queryKey: ['check-in-test-spots'], queryFn: () => getSpots({ areaCode: '1', sigunguCode: '23', limit: 20 }), enabled: authReady });
  useEffect(() => { const result = spotsQuery.data; if (!result?.data.length || result.meta.source === 'fallback') return; setSpots(result.data.map((spot, index) => index === 0 ? { ...spot, checkInCompleted: true } : index === 1 ? { ...spot, reviewStatus: 'PENDING', checkInCompleted: false } : spot)); }, [spotsQuery.data]);
  const displayedSpots = useMemo(() => spots.map((spot) => { const override = statusOverrides[String(spot.id)]; if (!override) return spot; return { ...spot, checkInCompleted: override === 'COMPLETED', reviewStatus: override === 'PENDING' ? 'PENDING' : undefined, checkInEnabled: override !== 'LOCKED' }; }), [spots, statusOverrides]);
  const applyPosition = (lat: number, lng: number) => { if (!Number.isFinite(lat) || !Number.isFinite(lng) || lat < -90 || lat > 90 || lng < -180 || lng > 180) { setError('위도는 -90~90, 경도는 -180~180 범위의 숫자여야 합니다.'); return; } setError(''); setNotice(''); setPosition({ lat, lng }); setLatitude(String(lat)); setLongitude(String(lng)); };
  const submit = (event: FormEvent) => { event.preventDefault(); applyPosition(Number(latitude), Number(longitude)); };
  const selectedDistance = selectedSpot ? calculateDistanceMeters(position.lat, position.lng, selectedSpot.location.lat, selectedSpot.location.lng) : 0;
  const selectedStatus = selectedSpot ? statusOverrides[String(selectedSpot.id)] ?? getSpotMarkerStatus(selectedSpot, selectedDistance, getCheckInRadius(selectedSpot)) : 'LOCKED';
  const forceStatus = (status: MarkerStatus) => { if (selectedSpot) setStatusOverrides((current) => ({ ...current, [String(selectedSpot.id)]: status })); };
  const tryCheckIn = async () => { if (!selectedSpot || selectedStatus !== 'AVAILABLE' || loading) return; setLoading(true); setNotice(''); const input: PositionInput = { ...position, accuracyM: 1, capturedAt: new Date().toISOString() }; try { const precheck = await precheckSpot(selectedSpot.id, input); if (!precheck.data.eligible) { setNotice(precheck.data.reasons?.[0] ?? '현장 인증 조건을 충족하지 못했습니다.'); return; } const checkIn = await createCheckIn(selectedSpot.id, input); setStatusOverrides((current) => ({ ...current, [String(selectedSpot.id)]: 'COMPLETED' })); setRewardPopup({ points: checkIn.data.reward.points, message: checkIn.data.status === 'REVIEW' ? '인증 결과를 확인하고 있어요.' : '체크인이 완료되었습니다.' }); } catch (caught) { const apiError = caught instanceof CheckInApiError; setNotice(apiError && caught.status === 501 ? '현장 인증 백엔드 기능 준비 중입니다.' : apiError && caught.status === 404 ? '현재 시범 운영 등록 장소가 아닙니다. (SPOT_NOT_FOUND)' : caught instanceof Error ? caught.message : '인증 처리에 실패했습니다.'); } finally { setLoading(false); } };
  return <main className="page check-in-test-page"><header className="simple-header"><p className="eyebrow">🧪 CHECK-IN TEST</p><h1>개발/테스트 전용</h1><p>지도를 클릭해 가상 위치를 이동하고, 포켓몬고 스타일 현장 인증을 시뮬레이션합니다.</p></header><CheckInMap position={position} spots={displayedSpots} selectedSpot={selectedSpot} onSelect={setSelectedSpot} onMapClick={applyPosition} />{selectedSpot && <section className="selected-test-spot"><h2>📍 선택한 장소 정보</h2><strong>{selectedSpot.title}</strong><p>현재 거리 {formatDistance(selectedDistance)}</p><p>{STATUS_LABEL[selectedStatus]}</p><div className="test-status-controls"><span>상태 강제 변경 테스트</span>{(['LOCKED', 'AVAILABLE', 'PENDING', 'COMPLETED'] as MarkerStatus[]).map((status) => <button key={status} type="button" onClick={() => forceStatus(status)}>{status}</button>)}</div><button type="button" className="primary-button" disabled={selectedStatus !== 'AVAILABLE' || loading} onClick={tryCheckIn}>{loading ? '인증 처리 중...' : '현장 인증하기'}</button>{notice && <p className="auth-error" role="alert">{notice}</p>}</section>}<section className="check-in-test-panel"><h2>🧪 테스트 위치</h2><p>지도를 클릭하면 해당 좌표로 즉시 Teleport합니다.</p><div className="test-location-coordinates"><span>위도 {position.lat.toFixed(6)}</span><span>경도 {position.lng.toFixed(6)}</span></div><form onSubmit={submit} className="test-location-form"><label>위도<input inputMode="decimal" value={latitude} onChange={(event) => setLatitude(event.target.value)} /></label><label>경도<input inputMode="decimal" value={longitude} onChange={(event) => setLongitude(event.target.value)} /></label><button type="submit" className="primary-button">위치 적용</button></form>{error && <p className="auth-error" role="alert">{error}</p>}</section><section className="check-in-test-results"><h2>주변 관광지 거리와 상태</h2>{spotsQuery.isPending && <p>관광지를 불러오는 중입니다.</p>}{spotsQuery.isError && <p className="auth-error">관광지를 불러오지 못했습니다. 샘플 데이터를 표시합니다.</p>}{displayedSpots.map((spot) => { const distance = calculateDistanceMeters(position.lat, position.lng, spot.location.lat, spot.location.lng); const status = statusOverrides[String(spot.id)] ?? getSpotMarkerStatus(spot, distance, spot.checkInRadiusM ?? CHECK_IN_RADIUS_METERS); return <article className="test-spot-row" key={spot.id} onClick={() => setSelectedSpot(spot)}><div><strong>{spot.title}</strong><small>{formatDistance(distance)}</small></div><span className={`test-spot-status test-spot-status--${status.toLowerCase()}`}>{STATUS_LABEL[status]}</span></article>; })}</section>{rewardPopup && <div className="check-in-modal-backdrop"><section className="check-in-modal check-in-modal--success" role="dialog" aria-modal="true"><h2>체크인 완료</h2><p>{rewardPopup.message}</p><strong className="check-in-modal__points">+{rewardPopup.points}P</strong><button type="button" className="primary-button" onClick={() => setRewardPopup(null)}>확인</button></section></div>}</main>;
}
